language: java
sudo: false
services:
- docker
before_install:
- pip install --user awscli
- export PATH=$PATH:$HOME/.local/bin
script:
- mvn clean verify
- docker-compose build
deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: fCoW7TcyrJ7gsISnNWPC0Ff3HyCUXzilTOB7pPwyAuAsse+Fz8Y1XevMVwqYWjaN1z/is3bZfT1WLele7pLmQhfwcBpC2XSUtOcNJrq462nb7gZqsQwMkot1jgraCzqKJNS3uwuA4P3vn9bjUcfsi3BnAiRG3ybDVXaO9RXtCHlpmdZhg62MijzCFf0wQIEE9hlyqz3o551fXmMoiwb7YCXllicbU/vJE9W7U1TRu5cMGQK6a0yR472HPD48hg3eRgU8Nv0JWIOi1DZLr1gESQozlF1HgSO5wkWIOs/Nqdma3HubYnGgR+QMHN2xcm9mQbCth94usTDO/T9WTVAQ0Nacv64Ktysq8U/Nf5qPjLdnh2RnM/mUiSJonxdfVx9HPXfDlUrBCkd359GxeW92hTyz4dkK8wODdjWTAI4f4FIIj+vvs5lF1NHE+N2cPN0GgFJQ7gx/c5vgffsymdLjwbWibbE0rkMeS0BqIRElpiVPG13vibdllDG9fK9i9d++xJ9PPBciRmUKi3w1c+sHTIQNgTMYekh9ylpG0+QUuVSrVsyZxUFEOXxODutrsPOj/DTt3GA4u4a2Zn0l6uBEKoUBBGJcfCnrtQuTxyNm50+Efrxsta5s0gDOPuKMf2lXLx5jX8q0+iSYxvSivwZMuA0+4bqwG9tAx8LXzHEoJww=
  secret_access_key:
    secure: HxJKgTnkV8jHzomRfJ8blrqBohNV2zgvIRc4752V5CKoS7nHM4wDk31SYk+g6xtqpGGMbqbJt6LYpZ8kUe7ncU66S3wrOJAFUBaZCSCMYEz5nKd3/RIVpdC4aD0hM2Wx93DGO+DM6T3aJZxzb/jxlVU0JYDQAwOytZHjOT5A1iXy16mchxuGA/r7f9mON5E5rEyaxIWrSD5W4gp9G4Ud87deOnUKX71tK9sZBIqTGuGTfll1hSkGocw5S3xXR+9wQNdkJvdZcHyeBkXJHZBGQCY0auDrr3av9md03R8bCyYivj3ogUHXz7h8XBDMdtsWiLKgodglaitKrp1twtVHFr7wxVlXFx2xGNyeXwb80c04Xcy9Mle5qqxmHP7ZOWXARKPrtrv6doKX6FkaJiTtdv/STTLsERF0MYLO/74G99vcSgSNs0Q9+andY60sJCblpq+MDwA2i9dycI98F3uEAWrs6EdPgPAU4NIAkb8bjw+SeL95L54BAIUj0jUa+aQ0rKJSCdlPLkTu5o7do8qFeqqIQAFz7AXLdsqR/WMq45l43EJYFyziUk71cke0MIngYuWs2+Z62nywQ5gc8AsuaH2fw53Tm0AW7LQYFhbYLJyxmMgq2sUCdE5+uAE+H6oD6VSNa04lvQyHRio6+5Jj0kjr4mQXGcui/vORy3Elkpc=
  app: docker-fibonacci
  env: DockerFibonacci-env.7z55r2iwvp.us-east-2.elasticbeanstalk.com
  bucket_name: elasticbeanstalk-us-east-2-804465465906

