language: java
sudo: false
services:
- docker
before_install:
- pip install --user awscli
- export PATH=$PATH:$HOME/.local/bin
script:
- mvn clean verify
- docker-compose build
deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESSKEYID
  secret_access_key: $ACCESSKEYSECRET
  region: us-east-2
  app: docker-fibonacci
  env: DockerFibonacci-env.7z55r2iwvp.us-east-2.elasticbeanstalk.com
  bucket_name: elasticbeanstalk-us-east-2-804465465906
